SELECT * FROM Mdb_Cus_Prog WHERE CUS_NO = '100055' and CUS_PROG_ID = 1139
SELECT * FROM Mdb_Cus_Prog_Rev WHERE CUS_PROG_ID = 1139
SELECT * FROM Mdb_Prog_Comment WHERE CUS_PROG_ID = 1139
SELECT * FROM Mdb_Cus_Prog_Item_List WHERE CUS_PROG_ID = 1139
SELECT * FROM Mdb_Cfg_Charge_Usage WHERE CUS_PROG_ID = 1139
SELECT * FROM Oeprcfil_Sql WHERE extra_14 = 1139 and ID = 13720240
SELECT *  FROM   Oeprcfil_Sql WITH (Nolock) 
 where ISNULL(Extra_14, 0) <> 0 AND ISNULL(Extra_14, 0) = 1139


SELECT	*
FROM MDB_CUS_PROG P WITH (Nolock) 
LEFT JOIN	MDB_CUS_PROG_ITEM_LIST I WITH (Nolock) ON P.CUS_PROG_ID = I.CUS_PROG_ID 
WHERE	P.CUS_PROG_ID = 1139 AND P.PROG_TYPE = 2 

13720232D

SELECT * FROM MDB_SYS_SCREEN_USER WHERE SCREEN_CD = 'CF-CTL-SPR-001' AND SCREEN_USER = 'iond'
