SELECT * FROM Mdb_Cus_Prog WHERE CUS_NO = '101202'
SELECT * FROM Mdb_Cus_Prog_Rev WHERE CUS_PROG_ID = 1149
SELECT * FROM Mdb_Prog_Comment WHERE CUS_PROG_ID = 1149
SELECT * FROM Mdb_Cus_Prog_Item_List WHERE CUS_PROG_ID = 1149
SELECT * FROM Mdb_Cfg_Charge_Usage WHERE CUS_PROG_ID = 1149
SELECT * FROM Oeprcfil_Sql WHERE extra_14 = 1149

SELECT		*
FROM		MDB_CUS_PROG P WITH (NOLOCK) 
LEFT JOIN	MDB_CUS_PROG_ITEM_LIST I WITH (NOLOCK) ON P.CUS_PROG_ID = I.CUS_PROG_ID 
LEFT JOIN  MDB_CFG_ENUM E WITH (NOLOCK) ON E.Enum_Cat = 'QUOTE_STEP_ID' AND P.Quote_Step_ID = E.enum_order 
WHERE	P.CUS_PROG_ID = 1149 AND PROG_TYPE = 3 



SELECT		P.CUS_PROG_ID,I.CUS_PROG_ITEM_LIST_ID,P.CUS_NO, '' AS ORD_STATUS, P.PROG_CSR , P.SPECTOR_CD AS Ord_No,
P.Start_Dt AS Ord_Dt, I.Item_Cd AS Item_No, RTRIM(ISNULL(I.ITEM_DESC, '')) + RTRIM(ISNULL(I.ITEM_Color, '')) AS Item_Desc, 
P.Quote_Step_ID, E.Enum_Value AS Quote_Step_Desc, 
CAST('' AS CHAR(2)) AS Qty_Ordered_Op, CAST(I.Min_Qty_Ord AS DECIMAL(13, 2)) AS Qty_Ordered, 
CAST('' AS CHAR(2)) AS Unit_Price_Op, I.Unit_Price, 
CAST('' AS CHAR(2)) AS Ext_Price_Op, ISNULL(I.Min_Qty_Ord, 0) * I.Unit_Price as Ext_Price, 
I.User_Login, I.Cus_Prog_Item_List_ID AS Line_Seq_No 
FROM		MDB_CUS_PROG P WITH (NOLOCK) 
LEFT JOIN	MDB_CUS_PROG_ITEM_LIST I WITH (NOLOCK) ON P.CUS_PROG_ID = I.CUS_PROG_ID 
LEFT JOIN  MDB_CFG_ENUM E WITH (NOLOCK) ON E.Enum_Cat = 'QUOTE_STEP_ID' AND P.Quote_Step_ID = E.enum_order 
WHERE	P.CUS_PROG_ID = 1149 AND PROG_TYPE = 3 