SELECT * FROM MDB_SYS_SCREEN_USER WHERE  SCREEN_CD = 'CF-CTL-SHP-001' AND  SCREEN_USER = 'iond'

SELECT		S.CUS_SHIP_ID, S.GROUP_CD, S.CUS_NO, S.CUS_ALT_ADR_CD, S.COUNTRY_CD,
S.PROG_ID, S.SHIP_VIA_CD, 
  CASE WHEN ISNULL(S.SHIP_COMMENTS, '') <> '' THEN S.SHIP_COMMENTS ELSE S.SHIP_VIA_ACCOUNT END AS SHIP_VIA_ACCOUNT, 
 S.ALWAYS_USE, S.NEVER_USE, S.PRINTER_COMMENT,
 S.PRINTER_INSTRUCTIONS, S.PACKER_COMMENT, S.PACKER_INSTRUCTIONS, 
 S.SHIP_INSTRUCTIONS_1, S.SHIP_INSTRUCTIONS_2, 
S.CMT_WHEN_SELECTED, S.NO_CHARGE, S.SAMPLES_ONLY, S.USER_LOGIN, S.UPDATE_TS 
FROM		MDB_CUS_SHIP S WITH (Nolock)
WHERE		S.CUS_NO = '100055' 
 ORDER BY	S.CUS_SHIP_ID 
 


  LEFT JOIN  SYCDEFIL_SQL C WITH (Nolock) ON S.SHIP_VIA_CD = C.SY_CODE AND Cd_Type = 'V' 
 WHERE		S.CUS_NO = '100055' 
 ORDER BY	S.CUS_SHIP_ID 
 
 SELECT top 2 * FROM MDB_CUS_SHIP order by CUS_SHIP_ID desc 
 SELECT TOP 2 * FROM SYCDEFIL_SQL where sy_code = 'AIR'   ORDER BY ID DESC 
 
 SELECT		S.SHIP_VIA_CD ,C.SY_CODE
  FROM		MDB_CUS_SHIP S WITH (Nolock)
  INNER JOIN  SYCDEFIL_SQL C WITH (Nolock) ON S.SHIP_VIA_CD = C.SY_CODE AND Cd_Type = 'V' 
 WHERE		S.CUS_NO = '100055' 
ORDER BY	S.CUS_SHIP_ID
 
select * FROM Mdb_Cus_Ship 
            WHERE  Cus_Ship_Id = 269
