SELECT		P.CUS_PROG_ID, I.CUS_PROG_ITEM_LIST_ID, P.CUS_NO, P.SPECTOR_CD, P.PROG_CD, P.PROG_CSR,
                       CASE WHEN ISNULL(P.PROG_DESC, '') <> '' THEN P.PROG_DESC ELSE P.PROG_COMMENTS END AS PROG_DESC,
            			P.START_DT, P.END_DT, I.ITEM_CD, I.ITEM_NO, I.MIN_QTY_ORD, 
            			CASE WHEN I.EQP_LEVEL = 0 THEN I.UNIT_PRICE ELSE NULL END AS UNIT_PRICE, 
            			CASE WHEN I.EQP_LEVEL IS NULL THEN P.EQP_LEVEL ELSE I.EQP_LEVEL END AS EQP_LEVEL, 
            			CASE WHEN I.EQP_LEVEL = 1 THEN I.EQP_COLUMN ELSE NULL END AS EQP_COLUMN, 
           			CASE WHEN I.EQP_LEVEL = 1 THEN I.EQP_PCT ELSE NULL END AS EQP_PCT, 
            			CONVERT(BIT, CASE WHEN P.APPROVED_DT IS NULL THEN 0 ELSE 1 END) AS IS_APPROVED, 
                       P.APPROVED_BY_US, P.APPROVED_BY_THEM, P.APPROVED_DT, P.USER_LOGIN, P.UPDATE_TS 
            FROM		MDB_CUS_PROG P WITH (Nolock) 
            LEFT JOIN	MDB_CUS_PROG_ITEM_LIST I WITH (Nolock) ON P.CUS_PROG_ID = I.CUS_PROG_ID 
            WHERE		P.PROG_TYPE = 1 
             AND P.CUS_NO = 'USS436'
              AND P.End_Dt >= CONVERT(DATE, GETDATE())