where CUS_PROG_ID in( 1157)
 where extra_14 in( 1157) 


select  * from MDB_CUS_PROG where cus_prog_id = 1163 order by CUS_PROG_ID desc
SELECT top 2 *  FROM Mdb_Cfg_Charge_Usage  order by CHARGE_USAGE_ID desc 

select top 50 * from oeprcfil_sql order by ID desc   


SELECT	CU.CUS_NO, CU.CUS_PROG_ID, CU.CHARGE_USAGE_ID, CU.CHARGE_ID, CU.DEC_MET_ID, 
  I.ITEM_NO, ISNULL(P.ID, 0) AS OEPRCFIL_ID
 FROM		MDB_CFG_CHARGE_USAGE CU WITH (NOLOCK) 
 LEFT JOIN	IMITMIDX_SQL I WITH (NOLOCK) ON CU.CHARGE_ID = I.EXTRA_14
 LEFT JOIN	OEPRCFIL_SQL P WITH (NOLOCK) ON CU.CUS_PROG_ID = P.EXTRA_14
 AND I.ITEM_NO = P.CD_TP_1_ITEM_NO 
 LEFT JOIN  MDB_CFG_DEC_MET DM WITH (Nolock) ON CU.DEC_MET_ID = DM.DEC_MET_ID 
 AND P.CD_TP = '1' 
 WHERE	CU.CUS_NO = 'USC752' AND 
  CU.CUS_PROG_ID = 1159 AND 
  CU.CHARGE_ID = 14
  ORDER BY	CHARGE_USAGE_ID, ITEM_NO

SELECT	CP.CUS_PROG_ID, C.CHARGE_ID, ISNULL(CU.CHARGE_USAGE_ID, 0) AS CHARGE_USAGE_ID, C.SHORT_DESC, CU.CUS_NO, 
CONVERT(BIT, (CASE ISNULL(CU.ALWAYS_USE, 0) WHEN 1 THEN 1 ELSE 0 END)) AS ALWAYS_USE, 
CONVERT(BIT, (CASE ISNULL(CU.NEVER_USE, 0) WHEN 1 THEN 1 ELSE 0 END)) AS NEVER_USE,
CONVERT(BIT, (CASE ISNULL(CU.NO_CHARGE, 0) WHEN 1 THEN 1 ELSE 0 END)) AS WAIVED, 
 CONVERT(BIT, (CASE ISNULL(CU.NO_CHARGE, 0) WHEN 1 THEN 0 ELSE 1 END)) AS NOT_WAIVED, 
CASE ISNULL(CU.NO_CHARGE, 0) WHEN 1 THEN CONVERT(VARCHAR(10), '')  ELSE CONVERT(VARCHAR(10), CU.UNIT_PRICE) END AS UNIT_PRICE, 
CU.WHEN_QTY_LT, CU.WHEN_QTY_GT, CU.WHEN_AMT_LT, CU.WHEN_AMT_GT,
CU.SEND_EMAIL, CU.EMAIL_TO, CU.WHEN_REQ, CU.BLIND, CU.COMMENTS, CU.AUTORIZED_BY
FROM 
(	SELECT	CUS.CUS_NO, C.*
FROM	arcusfil_sql CUS WITH (Nolock), MDB_CFG_CHARGE C WITH (Nolock)
 ) C 
LEFT JOIN	MDB_CFG_CHARGE_USAGE CU WITH (NOLOCK) ON c.charge_id = cu.CHARGE_ID and c.cus_no = cu.cus_no 
INNER JOIN	MDB_CFG_CHARGE CH WITH (NOLOCK) ON CU.CHARGE_ID = CH.CHARGE_ID 
LEFT JOIN  MDB_CUS_PROG CP WITH (NOLOCK) ON CU.CUS_PROG_ID = CP.CUS_PROG_ID AND ISNULL(CP.PROG_TYPE, 0) IN (0, 4) 
WHERE		C.CUS_NO = 'USS436' AND (CU.charge_usage_id IS NOT NULL) AND CP.PROG_TYPE = 4 
CU.CUS_NO = CP.CUS_NO AND 

SELECT * FROM arcusfil_sql WHERE cus_no = 'USC752'
SELECT * FROM MDB_CFG_CHARGE_USAGE WHERE CUS_NO = 'USC752' and CUS_PROG_ID = 1159
SELECT * FROM MDB_CFG_CHARGE WHERE CHARGE_ID = 14
SELECT * FROM MDB_CUS_PROG  WHERE CUS_PROG_ID = 1159 and CUS_NO = 'USC752'




SELECT  CU.CUS_NO, CU.CUS_PROG_ID, CU.CHARGE_USAGE_ID, CU.CHARGE_ID, CU.DEC_MET_ID,I.ITEM_NO,
 ISNULL(P.ID, 0) AS OEPRCFIL_ID 
 FROM  MDB_CFG_CHARGE_USAGE CU WITH (NOLOCK) 
 LEFT JOIN IMITMIDX_SQL I WITH (NOLOCK) ON CU.CHARGE_ID = I.EXTRA_14 
 LEFT JOIN OEPRCFIL_SQL P WITH (NOLOCK) ON CU.CUS_PROG_ID = P.EXTRA_14 AND I.ITEM_NO = P.CD_TP_1_ITEM_NO 
 and CU.Cus_NO = P.CD_TP_1_CUST_NO 
 LEFT JOIN  MDB_CFG_DEC_MET DM WITH (Nolock) ON CU.DEC_MET_ID = DM.DEC_MET_ID  AND P.CD_TP = '1' 
 WHERE CU.CUS_NO = 'USS437' AND CU.CUS_PROG_ID = 1163 AND CU.CHARGE_ID = 19 ORDER BY CHARGE_USAGE_ID, ITEM_NO 
 
  select * from oeprcfil_sql where ID =  13721004
 select * from oeprcfil_sql where ID =  13721005
  select * from oeprcfil_sql where ID =  13721006
  select * from oeprcfil_sql where ID =  13721007
  select top 4 * from oeprcfil_sql order by ID desc
select * from oeprcfil_sql where extra_14 = 1163

select * from MDB_CUS_PROG where CUS_PROG_ID = 1163
SELECT * FROM   Mdb_Cfg_Charge_Usage where CHARGE_USAGE_ID = 1480  order by CHARGE_USAGE_ID  desc
          



SELECT	CP.CUS_PROG_ID,	C.CHARGE_ID, ISNULL(CU.CHARGE_USAGE_ID, 0) AS CHARGE_USAGE_ID, C.SHORT_DESC, CU.CUS_NO, 
CONVERT(BIT, (CASE ISNULL(CU.ALWAYS_USE, 0) WHEN 1 THEN 1 ELSE 0 END)) AS ALWAYS_USE, 
CONVERT(BIT, (CASE ISNULL(CU.NEVER_USE, 0) WHEN 1 THEN 1 ELSE 0 END)) AS NEVER_USE, 
CONVERT(BIT, (CASE ISNULL(CU.NO_CHARGE, 0) WHEN 1 THEN 1 ELSE 0 END)) AS WAIVED, 
CONVERT(BIT, (CASE ISNULL(CU.NO_CHARGE, 0) WHEN 1 THEN 0 ELSE 1 END)) AS NOT_WAIVED, 
CASE ISNULL(CU.NO_CHARGE, 0) WHEN 1 THEN CONVERT(VARCHAR(10), '')  ELSE CONVERT(VARCHAR(10), CU.UNIT_PRICE) END AS UNIT_PRICE, 
CU.WHEN_QTY_LT, CU.WHEN_QTY_GT, CU.WHEN_AMT_LT, CU.WHEN_AMT_GT, 
CU.SEND_EMAIL, CU.EMAIL_TO, CU.WHEN_REQ, CU.BLIND, CU.COMMENTS, CU.AUTORIZED_BY 
FROM 
(	SELECT	CUS.CUS_NO, C.*
 FROM	arcusfil_sql CUS WITH (Nolock), MDB_CFG_CHARGE C WITH (Nolock)
) C 
LEFT JOIN	MDB_CFG_CHARGE_USAGE CU WITH (NOLOCK) ON c.charge_id = cu.CHARGE_ID and c.cus_no = cu.cus_no 
INNER JOIN	MDB_CFG_CHARGE CH WITH (NOLOCK) ON CU.CHARGE_ID = CH.CHARGE_ID 
LEFT JOIN  MDB_CUS_PROG CP WITH (NOLOCK) ON CU.CUS_NO = CP.CUS_NO AND CU.CUS_PROG_ID = CP.CUS_PROG_ID AND ISNULL(CP.PROG_TYPE, 0) IN (0, 4) 
WHERE		C.CUS_NO = 'USC225' AND (CU.charge_usage_id IS NOT NULL) AND CP.PROG_TYPE = 4 



SELECT cus_note_3 FROM ARCUSFIL_SQL WHERE cus_no = 'usc225' 

SELECT C.cus_no 
   FROM	ARCUSFIL_SQL C 
  LEFT JOIN  CICMPY P ON C.CUS_NO = P.CMP_CODE 
    WHERE  C.cus_note_3 = 'STAPLES USA'
   ORDER BY	C.CUS_NO 